pipeline:
  name: Teava5
  identifier: Teava5
  projectIdentifier: sz
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitConect
        repoName: harnesscd-example-apps
        build: <+input>
  stages:
    - stage:
        name: Bloc5
        identifier: Bloc5
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: hostname
        delegateSelectors:
          - docker-delegate-2
