pipeline:
  name: Teava8
  identifier: Teava8
  projectIdentifier: sz
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: GitConect
        repoName: harness2
        build: <+input>
  stages:
    - stage:
        name: Stagiu8
        identifier: Stagiu8
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: Windows
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Powershell
                    command: hostname
