pipeline:
  name: Build harness1
  identifier: Build_harness1_1765646805567
  projectIdentifier: default_project
  orgIdentifier: default
  stages:
    - stage:
        name: Build
        identifier: Build
        type: CI
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  type: Run
                  name: Echo Welcome Message
                  identifier: Echo_Welcome_Message
                  spec:
                    shell: Sh
                    command: echo "Welcome to Harness CI"
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: piscina
                harnessImageConnectorRef: account.harnessImage
                os: Linux
  properties:
    ci:
      codebase:
        connectorRef: Git
        repoName: harness1
        build: <+input>
