pipeline:
  name: Teava4
  identifier: Teava4
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Stagiu5
        identifier: Stagiu5
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          infrastructure:
            type: VM
            spec:
              type: Pool
              spec:
                poolName: piscina2
                harnessImageConnectorRef: account.harnessImage
                os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: hostname
  properties:
    ci:
      codebase:
        connectorRef: Git
        repoName: harness1
        build: <+input>
